# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '14.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 855)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(685, 540))
        MainWindow.setMaximumSize(QtCore.QSize(1110, 855))
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #2B2B2B;")
        self.centralwidget.setObjectName("centralwidget")
        self.analize_btn = QtWidgets.QPushButton(self.centralwidget)
        self.analize_btn.setGeometry(QtCore.QRect(40, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.analize_btn.setFont(font)
        self.analize_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.analize_btn.setObjectName("analize_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 41))
        self.frame.setStyleSheet("background-color: rgb(49, 80, 78)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(230, 0, 661, 41))
        self.label_4.setStyleSheet("color: white;\n"
"font: 18pt \"Century Gothic\";\n"
"font-weight: 700;")
        self.label_4.setObjectName("label_4")
        self.InputFile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.InputFile_btn.setGeometry(QtCore.QRect(40, 261, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.InputFile_btn.setFont(font)
        self.InputFile_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.InputFile_btn.setObjectName("InputFile_btn")
        self.input_path = QtWidgets.QLabel(self.centralwidget)
        self.input_path.setGeometry(QtCore.QRect(170, 261, 311, 30))
        self.input_path.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.input_path.setObjectName("input_path")
        self.Open_InputFile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Open_InputFile_btn.setGeometry(QtCore.QRect(40, 301, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.Open_InputFile_btn.setFont(font)
        self.Open_InputFile_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.Open_InputFile_btn.setObjectName("Open_InputFile_btn")
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(4, 41, 1101, 211))
        self.widget.setStyleSheet("background-color: black;")
        self.widget.setObjectName("widget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 421, 921, 71))
        self.textBrowser.setStyleSheet("border: 1px solid;\n"
"border-color: grey;\n"
"color: white;\n"
"background-color: black;")
        self.textBrowser.setObjectName("textBrowser")
        self.lang_name = QtWidgets.QLabel(self.centralwidget)
        self.lang_name.setGeometry(QtCore.QRect(40, 380, 61, 31))
        self.lang_name.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.lang_name.setObjectName("lang_name")
        self.language_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.language_comboBox.setGeometry(QtCore.QRect(100, 380, 70, 31))
        self.language_comboBox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.language_comboBox.setObjectName("language_comboBox")
        self.method_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.method_comboBox.setGeometry(QtCore.QRect(640, 260, 301, 31))
        self.method_comboBox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.method_comboBox.setObjectName("method_comboBox")
        self.method_name = QtWidgets.QLabel(self.centralwidget)
        self.method_name.setGeometry(QtCore.QRect(520, 260, 121, 31))
        self.method_name.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.method_name.setObjectName("method_name")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 500, 1091, 341))
        self.textBrowser_2.setStyleSheet("border: 1px solid;\n"
"border-color: grey;\n"
"background-color: black;\n"
"color: white;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lang_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.lang_name_2.setGeometry(QtCore.QRect(10, 421, 161, 71))
        self.lang_name_2.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.lang_name_2.setObjectName("lang_name_2")
        self.key_label = QtWidgets.QLabel(self.centralwidget)
        self.key_label.setGeometry(QtCore.QRect(190, 380, 71, 31))
        self.key_label.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.key_label.setObjectName("key_label")
        self.key_len_label = QtWidgets.QLabel(self.centralwidget)
        self.key_len_label.setGeometry(QtCore.QRect(170, 300, 171, 31))
        self.key_len_label.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.key_len_label.setObjectName("key_len_label")
        self.shift_count_label = QtWidgets.QLabel(self.centralwidget)
        self.shift_count_label.setGeometry(QtCore.QRect(520, 300, 191, 31))
        self.shift_count_label.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.shift_count_label.setObjectName("shift_count_label")
        self.key_len_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.key_len_spinbox.setGeometry(QtCore.QRect(340, 300, 91, 31))
        self.key_len_spinbox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.key_len_spinbox.setMinimum(1)
        self.key_len_spinbox.setMaximum(1000)
        self.key_len_spinbox.setObjectName("key_len_spinbox")
        self.shift_count_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.shift_count_spinbox.setGeometry(QtCore.QRect(710, 300, 91, 31))
        self.shift_count_spinbox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.shift_count_spinbox.setMaximum(1000)
        self.shift_count_spinbox.setObjectName("shift_count_spinbox")
        self.key_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.key_combobox.setGeometry(QtCore.QRect(260, 380, 841, 31))
        self.key_combobox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.key_combobox.setObjectName("key_combobox")
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(230, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.decrypt_btn.setFont(font)
        self.decrypt_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.ngram_len_label = QtWidgets.QLabel(self.centralwidget)
        self.ngram_len_label.setGeometry(QtCore.QRect(410, 340, 211, 31))
        self.ngram_len_label.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.ngram_len_label.setObjectName("ngram_len_label")
        self.ngram_len_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.ngram_len_spinbox.setGeometry(QtCore.QRect(620, 340, 91, 31))
        self.ngram_len_spinbox.setStyleSheet("background-color: black;\n"
"color: white;\n"
"font-family: Century Gothic;\n"
"font-size: 14px;")
        self.ngram_len_spinbox.setMaximum(1000)
        self.ngram_len_spinbox.setMinimum(3)
        self.ngram_len_spinbox.setObjectName("ngram_len_spinbox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analize_btn.setText(_translate("MainWindow", "Провести анализ"))
        self.label_4.setText(_translate("MainWindow", "КРИПТОАНАЛИЗ ПОЛИАЛФАВИТНЫХ ШИФРОВ"))
        self.InputFile_btn.setText(_translate("MainWindow", "Входной файл"))
        self.input_path.setText(_translate("MainWindow", "NO INPUT FILE"))
        self.Open_InputFile_btn.setText(_translate("MainWindow", "Открыть"))
        self.lang_name.setText(_translate("MainWindow", "ЯЗЫК"))
        self.method_name.setText(_translate("MainWindow", "АЛГОРИТМ"))
        self.lang_name_2.setText(_translate("MainWindow", "ВАРИАНТЫ\n"
"КЛЮЧЕЙ"))
        self.key_label.setText(_translate("MainWindow", "КЛЮЧ"))
        self.key_len_label.setText(_translate("MainWindow", "ДЛИНА КЛЮЧА"))
        self.shift_count_label.setText(_translate("MainWindow", "ЧИСЛО СДВИГОВ"))
        self.decrypt_btn.setText(_translate("MainWindow", "Рашифровать"))
        self.ngram_len_label.setText(_translate("MainWindow", "ДЛИНА N-ГРАММЫ"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
